version: '3.0'

services:
  web:
    build: .
    ports:
      - "5050:5000"
    volumes:
      - "./:/app"
    depends_on:
      - postgres_db
    env_file:
      - "./settings/env/.docker.env"

    restart: always
    command: flask run --host=0.0.0.0

  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azeez007
      POSTGRES_DB: umba

    volumes:
      - "/data:/var/lib/postgresql/data"

    ports:
      - "5432:5432"